repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: cba87736ffe2c479523d9d69919c1215084c7acc # v1.104.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
